ci: change to use GitHub actions
longhorn/go-iscsi-helper pull request #86
Opened 2024-04-29 06:58 UTC by FrankYang0529

#### Which issue(s) this PR fixes:
https://github.com/longhorn/longhorn/issues/8039

#### What this PR does / why we need it:

#### Special notes for your reviewer:

#### Additional documentation or context

2024-04-29 07:15 UTC, FrankYang0529 commented
Hi @derekbit, may you help to check the error test case? It looks like we didn't have CI for this repository.

2024-04-29 07:19 UTC, derekbit commented
```
iscsi_test.go:81:
    c.Assert(err, IsNil)
... value *errors.withStack = failed to execute: /usr/bin/nsenter [nsenter iscsiadm --version], output , stderr nsenter: failed to execute iscsiadm: No such file or directory
: exit status 1 ("failed to execute: /usr/bin/nsenter [nsenter iscsiadm --version], output , stderr nsenter: failed to execute iscsiadm: No such file or directory\n: exit status 1")

```

iSCSI service is not installed.
Check the installation in the [doc](https://longhorn.io/docs/1.6.1/deploy/install/#installing-open-iscsi) on different OSes.

2024-04-29 07:25 UTC, derekbit commented
Found found the Dockerfile.dapper relise ubuntu:16.04 base image. @FrankYang0529 Can you help create a ticket for migrating it to BCI image? Thank you.

2024-04-29 07:31 UTC, derekbit commented
```
value *errors.withStack = failed to execute: /usr/bin/nsenter [nsenter iscsiadm -m discovery -t sendtargets -p 172.17.0.2], output , stderr iscsiadm: c
```
kernel module is missing. Try `modprobe iscsi_tcp`.

2024-04-30 09:09 UTC, innobead requested changes
Need to fix the failed PR check.

```console
Running tests
modprobe: FATAL: Module iscsi_tcp not found in directory /lib/modules/6.5.0-1018-azure
Failed to load iscsi_tcp module
time="2024-04-30T06:37:02Z" level=fatal msg="exit status 1"
make: *** [Makefile:11: ci] Error 1
```

2024-04-30 09:09 UTC, innobead commented on Dockerfile.dapper
> +FROM registry.suse.com/bci/bci-base:15.6
Use golang 1.22 bci, and remove manual go installation.

2024-04-30 09:14 UTC, FrankYang0529 commented on Dockerfile.dapper
> +    make install
Because we didn't run Drone in this repository 😅

2024-05-11 04:11 UTC, derekbit commented
@FrankYang0529 Is it ready to review?

2024-05-13 06:44 UTC, FrankYang0529 commented
> @FrankYang0529 Is it ready to review?

This one is like go-spdk-helper and longhorn-spdk-engine. It need system modules like iSCSI daemon. Do you know how to start it in container? The testing error message is:

```
: exit status 12 ("failed to execute: /usr/bin/nsenter [nsenter iscsiadm -m discovery -t sendtargets -p 172.17.0.2], output , stderr Running in chroot, ignoring command 'start'\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Could not scan /sys/class/iscsi_transport.\nlibkmod: kmod_module_insert_module: could not find module by name='iscsi_tcp'\niscsiadm: Could not insert module tcp. Kmod error -2\niscsiadm: iSCSI driver tcp is not loaded. Load the module then retry the command.\niscsiadm: Could not perform SendTargets discovery: iSCSI driver not found. Please make sure it is loaded, and retry the operation\n: exit status 12")
```

2024-05-13 08:17 UTC, derekbit commented
> > @FrankYang0529 Is it ready to review?
> 
> This one is like go-spdk-helper and longhorn-spdk-engine. It need system modules like iSCSI daemon. Do you know how to start it in container? The testing error message is:
> 
> ```
> : exit status 12 ("failed to execute: /usr/bin/nsenter [nsenter iscsiadm -m discovery -t sendtargets -p 172.17.0.2], output , stderr Running in chroot, ignoring command 'start'\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Could not scan /sys/class/iscsi_transport.\nlibkmod: kmod_module_insert_module: could not find module by name='iscsi_tcp'\niscsiadm: Could not insert module tcp. Kmod error -2\niscsiadm: iSCSI driver tcp is not loaded. Load the module then retry the command.\niscsiadm: Could not perform SendTargets discovery: iSCSI driver not found. Please make sure it is loaded, and retry the operation\n: exit status 12")
> ```

It seems kernel module is not found.
Can you try `modprobe iscsi_tcp`?

2024-05-13 08:24 UTC, FrankYang0529 commented
> > > @FrankYang0529 Is it ready to review?
> > 
> > 
> > This one is like go-spdk-helper and longhorn-spdk-engine. It need system modules like iSCSI daemon. Do you know how to start it in container? The testing error message is:
> > ```
> > : exit status 12 ("failed to execute: /usr/bin/nsenter [nsenter iscsiadm -m discovery -t sendtargets -p 172.17.0.2], output , stderr Running in chroot, ignoring command 'start'\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Could not scan /sys/class/iscsi_transport.\nlibkmod: kmod_module_insert_module: could not find module by name='iscsi_tcp'\niscsiadm: Could not insert module tcp. Kmod error -2\niscsiadm: iSCSI driver tcp is not loaded. Load the module then retry the command.\niscsiadm: Could not perform SendTargets discovery: iSCSI driver not found. Please make sure it is loaded, and retry the operation\n: exit status 12")
> > ```
> 
> It seems kernel module is not found. Can you try `modprobe iscsi_tcp`?

We can't use `modprobe` command in container. It's like issue in longhorn-spdk-engine and go-spdk-helper.

2024-05-13 08:28 UTC, derekbit commented
> > > > @FrankYang0529 Is it ready to review?
> > > 
> > > 
> > > This one is like go-spdk-helper and longhorn-spdk-engine. It need system modules like iSCSI daemon. Do you know how to start it in container? The testing error message is:
> > > ```
> > > : exit status 12 ("failed to execute: /usr/bin/nsenter [nsenter iscsiadm -m discovery -t sendtargets -p 172.17.0.2], output , stderr Running in chroot, ignoring command 'start'\niscsiadm: can not connect to iSCSI daemon (111)!\niscsiadm: Could not scan /sys/class/iscsi_transport.\nlibkmod: kmod_module_insert_module: could not find module by name='iscsi_tcp'\niscsiadm: Could not insert module tcp. Kmod error -2\niscsiadm: iSCSI driver tcp is not loaded. Load the module then retry the command.\niscsiadm: Could not perform SendTargets discovery: iSCSI driver not found. Please make sure it is loaded, and retry the operation\n: exit status 12")
> > > ```
> > 
> > 
> > It seems kernel module is not found. Can you try `modprobe iscsi_tcp`?
> 
> We can't use `modprobe` command in container. It's like issue in longhorn-spdk-engine and go-spdk-helper.

You can modprobe it in the hostname space instead.

2024-07-03 10:35 UTC, derekbit commented
> Hi @derekbit, may you help to check the error test case? It looks like we didn't have CI for this repository.

You are right. I just realized we never run CI here.

2024-07-04 04:40 UTC, FrankYang0529 commented
> I think we can disable CI test as before and fix it later. WDYT?

Agree. The go-iscsi-helper works well. We just need to find a way to test it in the future. Thank you.

2024-07-04 04:41 UTC, merged